name: PHP Composer

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Composer: Validate"
        run: composer validate --strict

      - name: "Composer: Cache"
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: "Composer: Install"
        run: composer install --prefer-dist --no-progress

      - name: "Version: Increment"
        id: version_incrementer
        uses: reecetech/version-increment@2023.9.3

      - uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version_incrementer.outputs.version }}"
          artifacts: |
            src/**
            composer.json
            composer.lock


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
