name: PHP Composer

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: "Composer Install"
        run: composer install --prefer-dist --no-progress

      - name: "Get next version"
        id: version_incrementer
        uses: reecetech/version-increment@2023.9.3

      - name: "Update Composer Package Version"
        run: |
          composer config version ${{ steps.version_incrementer.outputs.version }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Incrementing version number"
          tagging_message: '${{ steps.version_incrementer.outputs.version }}'
          file_pattern: 'composer.json'


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
